spring.application.name=identity-service

# C?u hình k?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình JPA / Hibernate t? ??ng c?p nh?t c?u trúc b?ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# C?u hình JWT
jwt.secret=ThisIsAVerySecretKeyForIdentityServiceThatNeedsToBeAtLeast256BitsLong
jwt.expiration=3600000